server:
  port: 8085
  servlet:
    context-path: /job
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/challenge
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: desafio
  jpa:
    open-in-view: true
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database: mysql

