server:
  port: 8085
  servlet:
    context-path: /job
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/challenge?useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: desafio
    database-platform: org.hibernate.dialect.MySQL5Dialect
  jpa:
    open-in-view: true
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database: mysql

