server:
  port: 8083
  servlet:
    context-path: /avaliacao
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: hotmart
    password: desafio
    url: jdbc:postgresql://localhost:5432/challenge
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    open-in-view: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
    database: postgresql
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest    

rabbitmq:
  fila:
    avaliacaoProduto: avaliacaoProduto

  

 

  
  