version: '3'
services:

  desafio-rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
 
  desafio-mysqldb:
    image: mysql:8
    ports:
      - "3306:3306" 
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: desafio
      MYSQL_DATABASE: challenge
      
  desafio-postgresdb:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hotmart
      POSTGRES_PASSWORD: desafio
      POSTGRES_DB: challenge 
      
  desafio-adminer:
    image: adminer
    ports:
      - 9080:8080
    depends_on:
      - desafio-mysqldb
      - desafio-postgresdb
           
  desafio-cadastro:
    build: cadastro
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_USERNAME: hotmart
      SPRING_DATASOURCE_PASSWORD: desafio
      SPRING_DATASOURCE_URL: jdbc:postgresql://desafio-postgresdb:5432/challenge
      SPRING_RABBITMQ_HOST: desafio-rabbitmq      
    depends_on:
      - desafio-postgresdb
      - desafio-rabbitmq  

  desafio-venda:
    build: venda
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_USERNAME: hotmart
      SPRING_DATASOURCE_PASSWORD: desafio
      SPRING_DATASOURCE_URL: jdbc:postgresql://desafio-postgresdb:5432/challenge
      SPRING_RABBITMQ_HOST: desafio-rabbitmq      
    depends_on:
      - desafio-postgresdb
      - desafio-rabbitmq  

  desafio-avaliacao:
    build: avaliacao
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_USERNAME: hotmart
      SPRING_DATASOURCE_PASSWORD: desafio
      SPRING_DATASOURCE_URL: jdbc:postgresql://desafio-postgresdb:5432/challenge
      SPRING_RABBITMQ_HOST: desafio-rabbitmq
    depends_on:
      - desafio-postgresdb
      - desafio-rabbitmq  
    
  desafio-processa:
    build: processa
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: desafio
      SPRING_DATASOURCE_URL: jdbc:mysql://desafio-mysqldb:3306/challenge  
      SPRING_RABBITMQ_HOST: desafio-rabbitmq
    depends_on:
      - desafio-mysqldb 
      - desafio-rabbitmq
    
  desafio-noticia:
    build: noticia
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: desafio
      SPRING_DATASOURCE_URL: jdbc:mysql://desafio-mysqldb:3306/challenge
    depends_on:
      - desafio-mysqldb 

  desafio-busca:
    build: busca
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: desafio
      SPRING_DATASOURCE_URL: jdbc:mysql://desafio-mysqldb:3306/challenge
    depends_on:
      - desafio-mysqldb 
