server:
  port: 8082
  servlet:
    context-path: /venda
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: hotmart
    password: desafio
    url: jdbc:postgresql://localhost:5432/challenge
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    open-in-view: true
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database: postgresql
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    username: guest
    password: guest
    port: 5672 
   
rabbitmq:
  fila:
    avaliacaoProduto: avaliacaoProduto
    filaVenda: filaVenda

