server:
  port: 8084
  servlet:
    context-path: /processa
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/challenge
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: desafio
  jpa:
    open-in-view: true
    show-sql: false
    properties:
      javax:
        persistence:
          sharedCache: 
            mode: ENABLE_SELECTIVE     
    hibernate:
      ddl-auto: none
      cache:
        use_second_level_cache: true
        use_query_cache: true 
        region:
          factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory       
    database: mysql
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    username: guest
    password: guest
    port: 5672 

rabbitmq:
  fila:
    avaliacaoProduto: avaliacaoProduto
    filaVenda: filaVenda  