server:
  port: 8084
  servlet:
    context-path: /processa
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/challenge?useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: desafio
    database-platform: org.hibernate.dialect.MySQL5Dialect
  jpa:
    open-in-view: true
    show-sql: true
    generate-ddl: false
    hibernate:
      cache: 
        use_query_cache: true
        use_second_level_cache: true
        region:
          factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      ddl-auto: none
    database: mysql

rabbitmq:
  fila:
    avaliacaoProduto: avaliacaoProduto
    filaVenda: filaVenda  