server:
  port: 8081
  servlet:
    context-path: /crud
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: hotmart
    password: desafio
    url: jdbc:postgresql://localhost:5432/challenge
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    open-in-view: true
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database: postgresql